FROM tensorflow/tensorflow AS build
EXPOSE 9100

WORKDIR /srv
COPY ./* /srv/
RUN pip install flask tensorflow_hub
RUN python download-init-embeddings.py

# Package
# FROM tensorflow/tensorflow
# RUN apt install nodejs npm 
WORKDIR /srv
CMD python embeddings-service.py
